### PR TITLE
Allow install on php 8

### PR DESCRIPTION
**Pull request by Seldaek**

### CODE REVIEW

**Comment by Seldaek** [comment]
@h-bragg hey - I'd really appreciate a new release with this, allowing php 8 to be used. Let me know if I can do anything else to help out here.

**Comment by h-bragg** [comment]
> @h-bragg hey - I'd really appreciate a new release with this, allowing php 8 to be used. Let me know if I can do anything else to help out here.

Thanks for the interest.

If you could update the `.travis.yml` and the `Makefile` (`test-matrix` target) to support PHP8 too that would be good.
I expect some of the dependencies will need some updates

@biggianteye It looks like travis-ci.org has migrated to travis-ci.com. I think you would need to add this repo there and remove it from .org as this is in your organisation now / I don't have access.

**Comment by biggianteye** [comment]
> @biggianteye It looks like travis-ci.org has migrated to travis-ci.com; none of the builds are starting. I think you would need to add this repo there and remove it from .org as this is in your organisation now / I don't have access.

I'll try and sort this out next week.

**Comment by h-bragg** [comment]
> > @biggianteye It looks like travis-ci.org has migrated to travis-ci.com; none of the builds are starting. I think you would need to add this repo there and remove it from .org as this is in your organisation now / I don't have access.
> 
> I'll try and sort this out next week.

thanks 🙏

**Comment by Seldaek** [comment]
Hey, what I've done on all my repos is migrate to GH actions.. it isn't much work, and works much nicer IMO. I'll send a PR here to migrate away from travis if that's ok?

**Comment by Seldaek** [comment]
Eh well, did some basic version at https://github.com/graze/dog-statsd/pull/39 - unfortunately due to difficulties in supporting many PHPUnit versions + PHP versions at the same time, I had to do some compromises, and it's still not quite working, but I hope it'll help kick start the process for either of you to finish.

**Comment by biggianteye** [comment]
> > @biggianteye It looks like travis-ci.org has migrated to travis-ci.com; none of the builds are starting. I think you would need to add this repo there and remove it from .org as this is in your organisation now / I don't have access.
> 
> I'll try and sort this out next week.

Finally got a chance to look at this. I can see the notice about travis-ci.org shutting down, but the builds _are_ still starting up. eg. https://travis-ci.org/github/graze/dog-statsd/builds/755688920 They will eventually need moving over, and I'll try and sort that out at some point (or just move to GH actions).

**Comment by biggianteye** [comment]
This has now been done. Let me know if there are any problems.

**Pull request closed without merging**
